export const recipes: any = [
  {
    id: 1,
    title: 'Spaghetti Carbonara',
    duration: 30,
    servings: 4,
    author: { id: 1 },
  },
  {
    id: 2,
    title: 'Chicken Curry',
    duration: 45,
    servings: 6,
    author: { id: 2 },
  },
  {
    id: 3,
    title: 'Beef Stroganoff',
    duration: 40,
    servings: 5,
    author: { id: 3 },
  },
  {
    id: 4,
    title: 'Vegetable Stir Fry',
    duration: 25,
    servings: 3,
    author: { id: 4 },
  },
  {
    id: 5,
    title: 'Salmon Teriyaki',
    duration: 35,
    servings: 4,
    author: { id: 5 },
  },
  {
    id: 6,
    title: 'Margherita Pizza',
    duration: 20,
    servings: 2,
    author: { id: 1 },
  },
  {
    id: 7,
    title: 'Lamb Chops',
    duration: 50,
    servings: 4,
    author: { id: 2 },
  },
  {
    id: 8,
    title: 'French Onion Soup',
    duration: 60,
    servings: 6,
    author: { id: 3 },
  },
  {
    id: 9,
    title: 'Caesar Salad',
    duration: 15,
    servings: 2,
    author: { id: 4 },
  },
  {
    id: 10,
    title: 'Tacos',
    duration: 30,
    servings: 4,
    author: { id: 5 },
  },
];
