export const users: any = [
  {
    id: 1,
    firstName: 'John',
    lastName: 'Doe',
    email: 'john.doe@example.com',
    password: 'password123',
    recipes: [],
  },
  {
    id: 2,
    firstName: 'Jane',
    lastName: 'Smith',
    email: 'jane.smith@example.com',
    password: 'password123',
    recipes: [],
  },
  {
    id: 3,
    firstName: 'Robert',
    lastName: 'Brown',
    email: 'robert.brown@example.com',
    password: 'password123',
    recipes: [],
  },
  {
    id: 4,
    firstName: 'Emily',
    lastName: 'Clark',
    email: 'emily.clark@example.com',
    password: 'password123',
    recipes: [],
  },
  {
    id: 5,
    firstName: 'Michael',
    lastName: 'Johnson',
    email: 'michael.johnson@example.com',
    password: 'password123',
    recipes: [],
  },
];
